### PR TITLE
Encode fix

### LINKED ISSUE #82: [encode] Fix int64 type
**Where**
encode

**Bug detail**
We use int32 not int64.

### PR DESCRIPTION
**Pull request by hihiboss**
resolved: #82 

details:

Fixed encoding.

- [x] Test case

### CODE REVIEW

**Comment by zeroFruit** [comment]
I think it is duplicate with #86 ?

**Comment by hihiboss** [comment]
@zeroFruit 

Because #86 came out from this, it looks like this is duplicated!

File: encoding/encode.go [hunk 1]
```diff
@@ -18,36 +18,49 @@ package encoding
...
 	switch op := operand.(type) {
 	case int:
-		return nil
+		i, err := encodeInt(op)
+		if err != nil {
+			log.Fatal(err)
+		}
+
+		return i
+
```
Comment (junbeomlee) [inline encoding/encode.go:34]: It would be better to hand it over to return rather than to handle the error here.
```
func EncodeOperand(operand interface{}) ([]byte,error){
    return encodeInt(op)
}
```

File: encoding/encode.go [hunk 2]
```diff
@@ -18,36 +18,49 @@ package encoding
...
 	}
 }
 
-// Encode integer to hexadecimal bytes
-// ex) int 123 => 0x7b
+// EncodeOperand integer to hexadecimal bytes
+// ex) int 123 => 7b
 func encodeInt(operand int) ([]byte, error) {
-	s := strconv.FormatInt(int64(operand), 16)
+	s := fmt.Sprintf("%x", operand)
```
Comment (junbeomlee) [inline encoding/encode.go]: Returning size of []byte should be 32bits is it?

File: encoding/encode.go (hunk 1 above)
Comment (hihiboss) [reply encoding/encode.go:34]: I fixed!

File: encoding/encode.go (hunk 2 above)
Comment (hihiboss) [reply encoding/encode.go]: I edited it. Plz check and commit it!

**Comment by junbeomlee** [comment]
Did u check the size of bytes?!

**Review by junbeomlee — APPROVED** [review]

**Comment by junbeomlee** [comment]
Good work!
